[package]
name = "cloudterm"
version = "1.0.9"
description = "CloudTerm — cliente de terminal SSH/SFTP con paneles de transferencia e IA"
authors = ["pilahito <57416155+pilahito@users.noreply.github.com>"]
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/pilahito/cloudterm"

[lib]
name = "cloudterm_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
tauri-plugin-os = "2"

tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "net",
  "time",
  "io-util",
  "sync",
  "fs",
  "process",
] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

sha2 = "0.10"
base64 = "0.21"
rand = "0.8"
url = "2"

hmac = "0.12"
sha1 = "0.10"
argon2 = "0.6"
qrcode = "0.14"

chrono = "0.4"

russh = "0.63.3"
russh-sftp = "3.0.0"
suppaftp = { version = "12.0.0", features = ["tokio-rustls-ring"] }

sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "sqlite", "migrate", "macros"] }
futures-util = "0.3.34"
reqwest = { version = "0.13.5", features = ["json", "stream", "form", "query"] }

[target.'cfg(not(target_os = "android"))'.dependencies]
keyring = { version = "3", features = ["linux-native", "apple-native", "windows-native", "crypto-rust"] }
portable-pty = "0.8"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
