LangString addOrReinstall ${LANG_SIMPCHINESE} "添加/重新安装组件"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已经安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已经安装。请选择要执行的操作，然后单击“下一步”继续。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！请先关闭后再试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！$\n单击“确定”以结束进程。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择要执行的维护操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择安装 ${PRODUCTNAME} 的方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "不要卸载"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不要卸载（此安装程序禁用未卸载的降级）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法结束 {{product_name}}。请先关闭后再试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "已安装更新版本的 ${PRODUCTNAME}。不建议安装旧版本。若仍要继续，请先卸载当前版本。选择操作后单击“下一步”。"
LangString older ${LANG_SIMPCHINESE} "较旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "系统已安装 $R4 版本的 ${PRODUCTNAME}。建议先卸载当前版本。选择操作后单击“下一步”。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "此安装程序禁用降级。请使用图形安装程序。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载！"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "安装前卸载"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "无法安装 WebView2。CloudTerm 需要它才能运行。请重新启动安装程序。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "错误：下载 WebView2 失败 — $0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 引导程序下载成功"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 引导程序..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "错误：安装 WebView2 失败，退出代码 $1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 安装成功"
LangString deleteAppData ${LANG_SIMPCHINESE} "删除应用程序数据"

LangString welcomePageTitle ${LANG_SIMPCHINESE} "欢迎使用 CloudTerm 安装程序"
LangString welcomePageText ${LANG_SIMPCHINESE} "CloudTerm — 桌面 SSH 和 SFTP 客户端。$\r$\n$\r$\n• SSH 终端$\r$\n• SFTP 文件传输$\r$\n• Pixel Agents（可视化代理监控）$\r$\n$\r$\n仓库：https://github.com/pilahito/cloudterm$\r$\n$\r$\n安装向导将引导您完成安装。单击“下一步”继续。"
LangString finishPageTitle ${LANG_SIMPCHINESE} "CloudTerm 已安装"
LangString finishPageText ${LANG_SIMPCHINESE} "谢谢。CloudTerm 已成功安装。$\r$\n$\r$\n您可以立即启动，或稍后从开始菜单打开。$\r$\n$\r$\nhttps://github.com/pilahito/cloudterm"
LangString launchCloudTerm ${LANG_SIMPCHINESE} "启动 CloudTerm"
