LangString addOrReinstall ${LANG_SPANISH} "Añadir o reinstalar componentes"
LangString alreadyInstalled ${LANG_SPANISH} "Ya está instalado"
LangString alreadyInstalledLong ${LANG_SPANISH} "${PRODUCTNAME} ${VERSION} ya está instalado. Seleccione la operación que desee realizar y pulse Siguiente para continuar."
LangString appRunning ${LANG_SPANISH} "¡{{product_name}} está abierto! Ciérrelo e inténtelo de nuevo."
LangString appRunningOkKill ${LANG_SPANISH} "¡{{product_name}} está abierto!$\nPulse Aceptar para cerrarlo."
LangString chooseMaintenanceOption ${LANG_SPANISH} "Elija la operación de mantenimiento que desee realizar."
LangString choowHowToInstall ${LANG_SPANISH} "Elija cómo desea instalar ${PRODUCTNAME}."
LangString createDesktop ${LANG_SPANISH} "Crear acceso directo en el escritorio"
LangString dontUninstall ${LANG_SPANISH} "No desinstalar"
LangString dontUninstallDowngrade ${LANG_SPANISH} "No desinstalar (bajar de versión sin desinstalar está deshabilitado)"
LangString failedToKillApp ${LANG_SPANISH} "No se ha podido cerrar {{product_name}}. Ciérrelo e inténtelo de nuevo."
LangString installingWebview2 ${LANG_SPANISH} "Instalando WebView2..."
LangString newerVersionInstalled ${LANG_SPANISH} "Ya hay una versión más reciente de ${PRODUCTNAME}. No se recomienda instalar una anterior. Si realmente quiere, desinstale primero la actual. Seleccione la operación y pulse Siguiente."
LangString older ${LANG_SPANISH} "anterior"
LangString olderOrUnknownVersionInstalled ${LANG_SPANISH} "Hay una versión $R4 de ${PRODUCTNAME} en el sistema. Es recomendable desinstalarla antes. Seleccione la operación y pulse Siguiente."
LangString silentDowngrades ${LANG_SPANISH} "Bajar de versión está deshabilitado en este instalador. Use el asistente gráfico.$\n"
LangString unableToUninstall ${LANG_SPANISH} "No se ha podido desinstalar."
LangString uninstallApp ${LANG_SPANISH} "Desinstalar ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SPANISH} "Desinstalar antes de instalar"
LangString unknown ${LANG_SPANISH} "desconocida"
LangString webview2AbortError ${LANG_SPANISH} "No se ha podido instalar WebView2. CloudTerm no puede ejecutarse sin él. Reinicie el instalador."
LangString webview2DownloadError ${LANG_SPANISH} "Error: no se ha podido descargar WebView2 — $0"
LangString webview2DownloadSuccess ${LANG_SPANISH} "El instalador de WebView2 se descargó correctamente."
LangString webview2Downloading ${LANG_SPANISH} "Descargando WebView2..."
LangString webview2InstallError ${LANG_SPANISH} "Error: la instalación de WebView2 falló con el código $1."
LangString webview2InstallSuccess ${LANG_SPANISH} "WebView2 se instaló correctamente."
LangString deleteAppData ${LANG_SPANISH} "Eliminar los datos de la aplicación"

LangString welcomePageTitle ${LANG_SPANISH} "Bienvenido al instalador de CloudTerm"
LangString welcomePageText ${LANG_SPANISH} "CloudTerm — cliente SSH y SFTP de escritorio.$\r$\n$\r$\n• Terminal SSH$\r$\n• Transferencia SFTP$\r$\n• Pixel Agents (monitoreo visual de agentes)$\r$\n$\r$\nRepositorio: https://github.com/pilahito/cloudterm$\r$\n$\r$\nEl asistente le guiará durante la instalación. Pulse Siguiente para continuar."
LangString finishPageTitle ${LANG_SPANISH} "CloudTerm se ha instalado"
LangString finishPageText ${LANG_SPANISH} "Gracias. CloudTerm se instaló correctamente.$\r$\n$\r$\nPuede abrirlo ahora o más tarde desde el menú Inicio.$\r$\n$\r$\nhttps://github.com/pilahito/cloudterm"
LangString launchCloudTerm ${LANG_SPANISH} "Iniciar CloudTerm"
